name: Hello Flow
on:
  schedule:
    - cron: '*/5 * * * *'   # a cada 5 minutos
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Diga oi
        run: echo "Hello World!"
      - name: Diga valeu
        run: echo "Valeu - bye!"
